### ISSUE TITLE
Match lists with checkboxes via regex

### ISSUE THREAD

**Issue by DivineDominion** [iltempo/thearchive-tasks-plugin#1]
This looks really cool!

I was under the impression that the checkbox syntax needs to be part of a list, not just anywhere, so e.g.

```
[ ] box
```

will not render:

-----

[ ] box

-----

So maybe the expression needs to be changed to accept `[-*] \[ \]` for unordered, and `[\d]+\. \[ \]` for ordered lists as a regular expression?

**Comment by iltempo** [comment]
@DivineDominion Thank you for the feedback.

My personal notes regarding tasks and lists could be more consistent at the moment. Some tasks I wrote without a dash. This is why my regular expression is lazy. But I am happy to change that.

Are ordered lists allowed? On GitHub, it does not seem to be specified.
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists

Do you have an example of an ordered task list?

**Comment by DivineDominion** [comment]
1. [ ] test (`1.`)

and

- [ ] test `-`

and

* [ ] test `*` 

it looks like it's more lenient than documented (phew)

**Comment by iltempo** [comment]
I merged the regular expressions into one and created a new 1.1.0 release.

**Comment by woodenzen** [comment]
I'd suggest making the regex as lazy as possible. Users can be lazy. 
/\[ \] .*/g 
This is fast and covers all creative uses of the checkbox. 
Now, I want to create a companion plugin to check the todo box with a hotkey. 

I'll try to watch closer to where conversations are happening.
