### ISSUE TITLE
The resulting task list is not rendering correctly as Markdown

### ISSUE THREAD

**Issue by iltempo** [iltempo/thearchive-tasks-plugin#5]
The resulting task list of the plugin can not be rendered correctly as a list below the wiki links.
The reason is most likely a missing new line between the wiki link and the list below.

https://forum.zettelkasten.de/discussion/comment/21610/#Comment_21610

![0kgwiix0r0ma](https://github.com/user-attachments/assets/01ece07c-2076-40af-9499-92139d7264dc)

**Comment by woodenzen** [comment]
You are right. A \n is needed for Marked2 to render this correctly.

But there is still a problem with  "Invalid intended task without list" and "not a task but brackets somewhere in the text." If I remove them, Marked2 will render this perfectly. I need to discover why these false positives are captured. 
<img width="691" alt="Screenshot 2024-10-08 at 7 14 37 AM" src="https://github.com/user-attachments/assets/10cd79c2-754d-4876-9cdf-4d7962a85ffa">

**Comment by woodenzen** [comment]
// Write note links
    body += "\n[[" + note.filename + "]]\n\n";

**Comment by iltempo** [comment]
@woodenzen, can you please try the latest version?

https://github.com/iltempo/thearchive-tasks-plugin/releases/tag/1.2.0

**Comment by woodenzen** [comment]
Worked great. Found all legal todos and formated them correctly in Marked2.
